{{- if and .Values.config_values.auth.enabled (not .Values.config_values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "zookeeper.namespace" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.config_values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.config_values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.config_values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.config_values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  client-password: {{ include "zookeeper.clientPassword" . | b64enc | quote }}
  server-password: {{ include "zookeeper.serverPasswords" . | b64enc | quote }}
{{- end }}
